version: '3'
services:

  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
    ports:
      - 5432:5432

  db-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: db-test
    ports:
      - 5432:5432
